In [1]:
import pandas as pd

df = pd.read_csv("global-data-on-sustainable-energy.csv")
df.iloc[19:41]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
19,Afghanistan,2019,97.70,31.90,9.58,4620000.0,18.51,0.18,0.0,0.89,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.939110,67.709953
20,Afghanistan,2020,97.70,33.20,9.35,NaN,NaN,0.12,0.0,0.68,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
21,Albania,2000,100.00,38.20,NaN,NaN,NaN,0.14,0.0,4.55,...,9029.43750,4.13,3170.000000,NaN,6.946217,1126.683340,105,28748.0,41.153332,20.168331
22,Albania,2001,100.00,40.50,NaN,NaN,NaN,0.13,0.0,3.52,...,8635.53200,3.89,3230.000000,NaN,8.293313,1281.659826,105,28748.0,41.153332,20.168331
23,Albania,2002,100.00,43.20,NaN,NaN,NaN,0.16,0.0,3.48,...,9443.55500,4.10,3759.999990,NaN,4.536524,1425.124219,105,28748.0,41.153332,20.168331
24,Albania,2003,100.00,46.40,NaN,NaN,NaN,0.10,0.0,5.12,...,10756.61200,3.80,4070.000172,NaN,5.528637,1846.120121,105,28748.0,41.153332,20.168331
25,Albania,2004,100.00,49.00,NaN,NaN,NaN,0.13,0.0,5.41,...,11586.95100,3.96,4250.000000,NaN,5.514668,2373.581292,105,28748.0,41.153332,20.168331
26,Albania,2005,100.00,51.90,NaN,NaN,NaN,0.07,0.0,5.32,...,11545.61600,3.75,4030.000210,NaN,5.526424,2673.786584,105,28748.0,41.153332,20.168331
27,Albania,2006,100.00,54.80,NaN,NaN,NaN,0.09,0.0,4.95,...,10976.72800,3.46,4010.000229,NaN,5.902659,2972.742924,105,28748.0,41.153332,20.168331
28,Albania,2007,100.00,58.10,NaN,NaN,NaN,0.07,0.0,2.76,...,9534.87400,3.12,4139.999866,NaN,5.983260,3595.038057,105,28748.0,41.153332,20.168331
29,Albania,2008,100.00,60.80,NaN,NaN,NaN,0.07,0.0,3.76,...,10499.32800,3.01,4079.999924,NaN,7.500041,4370.539925,105,28748.0,41.153332,20.168331
30,Albania,2009,100.00,63.60,NaN,NaN,NaN,0.00,0.0,5.20,...,11524.42800,2.98,4219.999790,NaN,3.354289,4114.134899,105,28748.0,41.153332,20.168331
31,Albania,2010,100.00,66.50,NaN,NaN,NaN,0.00,0.0,7.49,...,12377.50400,2.85,4449.999809,NaN,3.706938,4094.348386,105,28748.0,41.153332,20.168331
32,Albania,2011,100.00,68.90,NaN,NaN,NaN,0.06,0.0,4.09,...,10854.64900,2.91,4849.999905,NaN,2.545406,4437.142612,105,28748.0,41.153332,20.168331
33,Albania,2012,99.90,71.30,NaN,NaN,NaN,0.00,0.0,4.68,...,10652.80900,2.57,4360.000134,NaN,1.417243,4247.630047,105,28748.0,41.153332,20.168331
34,Albania,2013,100.00,73.15,NaN,NaN,NaN,0.00,0.0,6.89,...,13392.77400,2.96,4440.000057,NaN,1.002018,4413.062005,105,28748.0,41.153332,20.168331
35,Albania,2014,99.95,74.60,NaN,NaN,NaN,0.00,0.0,4.68,...,11809.46100,2.93,4820.000172,NaN,1.774449,4578.633208,105,28748.0,41.153332,20.168331
36,Albania,2015,99.98,76.20,NaN,NaN,NaN,0.00,0.0,5.84,...,11824.31400,2.69,4619.999886,NaN,2.218726,3952.802538,105,28748.0,41.153332,20.168331
37,Albania,2016,99.89,77.80,NaN,NaN,NaN,0.00,0.0,7.70,...,13823.74800,2.68,4480.000019,NaN,3.314981,4124.055390,105,28748.0,41.153332,20.168331
38,Albania,2017,99.89,78.70,NaN,NaN,NaN,0.00,0.0,4.48,...,12802.36000,2.69,5139.999866,NaN,3.802227,4531.019374,105,28748.0,41.153332,20.168331
39,Albania,2018,100.00,79.80,NaN,NaN,NaN,0.00,0.0,8.47,...,14609.70100,2.57,5110.000134,NaN,4.019360,5287.663694,105,28748.0,41.153332,20.168331
40,Albania,2019,100.00,80.70,NaN,NaN,NaN,0.00,0.0,5.17,...,11585.55500,2.50,4829.999924,NaN,2.113420,5395.659532,105,28748.0,41.153332,20.168331

In [2]:
df.shape

(3649, 21)

In [3]:
df['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'French Guiana', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Tajikistan', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [4]:
paises_continente = {
    'Afghanistan': 'Asia',
    'Albania': 'Europe',
    'Algeria': 'Africa',
    'Andorra': 'Europe',
    'Angola': 'Africa',
    'Antigua and Barbuda': 'Centro America, Caribe',
    'Argentina': 'South America',
    'Armenia': 'Asia',
    'Aruba':'Centro America, Caribe', 
    'Australia': 'Oceania',
    'Austria': 'Europe',
    'Azerbaijan': 'Asia',
    'Bahamas': 'Centro America, Caribe',
    'Bahrain': 'Asia',
    'Bangladesh': 'Asia',
    'Barbados': 'Centro America, Caribe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Belize': 'Centro America, Caribe',
    'Benin': 'Africa',
    'Bermuda':'Centro America, Caribe', 
    'Bhutan': 'Asia',
    'Bolivia': 'South America',
    'Bosnia and Herzegovina': 'Europe',
    'Botswana': 'Africa',
    'Brazil': 'South America',
    'Brunei': 'Asia',
    'Bulgaria': 'Europe',
    'Burkina Faso': 'Africa',
    'Burundi': 'Africa',
    'Cabo Verde': 'Africa',
    'Cambodia': 'Asia',
    'Cameroon': 'Africa',
    'Canada': 'North America',
    'Cayman Islands':'Centro America, Caribe', 
    'Central African Republic': 'Africa',
    'Chad': 'Africa',
    'Chile': 'South America',
    'China': 'Asia',
    'Colombia': 'South America',
    'Comoros': 'Africa',
    'Congo': 'Africa',
    'Costa Rica': 'Centro America, Caribe',
    'Croatia': 'Europe',
    'Cuba': 'Centro America, Caribe',
    'Cyprus': 'Asia',
    'Czechia': 'Europe',
    'Denmark': 'Europe',
    'Djibouti': 'Africa',
    'Dominica': 'Centro America, Caribe',
    'Dominican Republic': 'Centro America, Caribe',
    'East Timor': 'Asia',
    'Ecuador': 'South America',
    'Egypt': 'Africa',
    'El Salvador': 'Centro America, Caribe',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Estonia': 'Europe',
    'Eswatini': 'Africa',
    'Ethiopia': 'Africa',
    'Fiji': 'Oceania',
    'Finland': 'Europe',
    'France': 'Europe',
    'French Guiana':'South America',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Georgia': 'Asia',
    'Germany': 'Europe',
    'Ghana': 'Africa',
    'Greece': 'Europe',
    'Grenada': 'Centro America, Caribe',
    'Guatemala': 'Centro America, Caribe',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Guyana': 'South America',
    'Haiti': 'Centro America, Caribe',
    'Honduras': 'Centro America, Caribe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran': 'Asia',
    'Iraq': 'Asia',
    'Ireland': 'Europe',
    'Israel': 'Asia',
    'Italy': 'Europe',
    'Jamaica': 'Centro America, Caribe',
    'Japan': 'Asia',
    'Jordan': 'Asia',
    'Kazakhstan': 'Asia',
    'Kenya': 'Africa',
    'Kiribati': 'Oceania',
    'Korea, North': 'Asia',
    'Korea, South': 'Asia',
    'Kosovo': 'Europe',
    'Kuwait': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Laos': 'Asia',
    'Latvia': 'Europe',
    'Lebanon': 'Asia',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Madagascar': 'Africa',
    'Malawi': 'Africa',
    'Malaysia': 'Asia',
    'Maldives': 'Asia',
    'Mali': 'Africa',
    'Malta': 'Europe',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Mexico': 'North America',
    'Mongolia': 'Asia',
    'Montenegro': 'Europe',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Myanmar': 'Asia',
    'Namibia': 'Africa',
    'Nauru': 'Oceania',
    'Nepal': 'Asia',
    'Netherlands': 'Europe',
    'New Caledonia': 'Oceania',
    'New Zealand': 'Oceania',
    'Nicaragua': 'Centro America, Caribe',
    'Niger': 'Africa',
    'Nigeria': 'Africa',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Oman': 'Asia',
    'Pakistan': 'Asia',
    'Panama': 'Centro America, Caribe',
    'Papua New Guinea': 'Oceania',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Philippines': 'Asia',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Puerto Rico': 'Centro America, Caribe',
    'Qatar': 'Asia',
    'Romania': 'Europe',
    'Rwanda': 'Africa',
    'Saint Kitts and Nevis': 'Centro America, Caribe',
    'Saint Lucia': 'Centro America, Caribe',
    'Saint Vincent and the Grenadines': 'Centro America, Caribe',
    'Samoa': 'Oceania',
    'Sao Tome and Principe': 'Africa',
    'Saudi Arabia': 'Asia',
    'Senegal': 'Africa',
    'Serbia': 'Europe',
    'Seychelles': 'Africa',
    'Sierra Leone': 'Africa',
    'Singapore': 'Asia',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Solomon Islands': 'Oceania',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Sudan': 'Africa',
    'Spain': 'Europe',
    'Sri Lanka': 'Asia',
    'Sudan': 'Africa',
    'Suriname': 'South America',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Tajikistan': 'Asia',
    'Thailand': 'Asia',
    'Togo': 'Africa',
    'Tonga': 'Oceania',
    'Trinidad and Tobago': 'Centro America, Caribe',
    'Tunisia': 'Africa',
    'Turkey': 'Asia',
    'Turkmenistan': 'Asia',
    'Tuvalu': 'Oceania',
    'Uganda': 'Africa',
    'Ukraine': 'Europe',
    'United Arab Emirates': 'Asia',
    'United Kingdom': 'Europe',
    'United States': 'North America',
    'Uruguay': 'South America',
    'Uzbekistan': 'Asia',
    'Vanuatu': 'Oceania',
    'Yemen': 'Asia',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa'
}

In [5]:
df['Continente'] = df['Entity'].map(paises_continente)
df.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude,Continente
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,Asia
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,Asia
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953,Asia
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953,Asia
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953,Asia

In [6]:
df.shape

(3649, 22)

In [7]:
df['Continente'] = df['Entity'].map(paises_continente)
columna_continente = df.pop('Continente')
df.insert(1, 'Continente', columna_continente)
df.head()

,Entity,Continente,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,Asia,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [129]:
df.columns = [e.lower().replace(" ", "_").replace("\n","_").replace("-","_").replace("\\n","_").replace("us_$","usd") for e in df.columns]
df.head()

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(usd),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.93911,67.709953

In [60]:
df['density_(p/km2)'] = df['density_(p/km2)'].str.replace(',', '.').apply(lambda x:df['density_(p/km2)'].get(x,x))

In [69]:
df['density_(p/km2)'] = pd.to_numeric(df["density_(p/km2)"])

In [72]:
df.dtypes

entity                                                               object
continente                                                           object
year                                                                  int64
access_to_electricity_(%_of_population)                             float64
access_to_clean_fuels_for_cooking                                   float64
renewable_electricity_generating_capacity_per_capita                float64
financial_flows_to_developing_countries_(us_$)                      float64
renewable_energy_share_in_the_total_final_energy_consumption_(%)    float64
electricity_from_fossil_fuels_(twh)                                 float64
electricity_from_nuclear_(twh)                                      float64
electricity_from_renewables_(twh)                                   float64
low_carbon_electricity_(%_electricity)                              float64
primary_energy_consumption_per_capita_(kwh/person)                  float64
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         float64
value_co2_emissions_kt_by_country                                   float64
renewables_(%_equivalent_primary_energy)                            float64
gdp_growth                                                          float64
gdp_per_capita                                                      float64
density_(p/km2)                                                     float64
land_area(km2)                                                      float64
latitude                                                            float64
longitude                                                           float64
dtype: object

In [169]:
df_af = df.loc[df['entity']=='Afghanistan']
df_af

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(usd),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.613591,6.20,9.22,2.000000e+04,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.20,8.86,1.300000e+05,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.20,8.47,3.950000e+06,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.50,8.09,2.597000e+07,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.90,7.75,3.296947e+07,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.93911,67.709953
5,Afghanistan,Asia,2005,25.390894,12.20,7.51,9.830000e+06,33.88,0.34,0.0,...,252.06912,1.41,1549.999952,NaN,11.229715,242.031313,60.0,652230.0,33.93911,67.709953
6,Afghanistan,Asia,2006,30.718690,13.85,7.40,1.062000e+07,31.89,0.20,0.0,...,304.42090,1.50,1759.999990,NaN,5.357403,263.733602,60.0,652230.0,33.93911,67.709953
7,Afghanistan,Asia,2007,36.051010,15.30,7.25,1.575000e+07,28.78,0.20,0.0,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60.0,652230.0,33.93911,67.709953
8,Afghanistan,Asia,2008,42.400000,16.70,7.49,1.617000e+07,21.17,0.19,0.0,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60.0,652230.0,33.93911,67.709953
9,Afghanistan,Asia,2009,46.740050,18.40,7.50,9.960000e+06,16.53,0.16,0.0,...,975.04816,2.25,4880.000114,NaN,21.390528,437.268740,60.0,652230.0,33.93911,67.709953
10,Afghanistan,Asia,2010,42.700000,20.00,8.27,3.650000e+07,15.15,0.19,0.0,...,1182.89200,2.46,7110.000134,NaN,14.362441,543.306526,60.0,652230.0,33.93911,67.709953
11,Afghanistan,Asia,2011,43.222020,21.80,8.13,2.869000e+07,12.61,0.18,0.0,...,1436.11430,3.23,8930.000305,NaN,0.426355,591.190030,60.0,652230.0,33.93911,67.709953
12,Afghanistan,Asia,2012,69.100000,23.00,9.29,6.263000e+07,15.36,0.14,0.0,...,1324.12110,2.61,8079.999924,NaN,12.752287,638.845852,60.0,652230.0,33.93911,67.709953
13,Afghanistan,Asia,2013,68.290650,24.80,9.10,2.684600e+08,16.86,0.22,0.0,...,1060.79260,2.46,5989.999771,NaN,5.600745,624.315454,60.0,652230.0,33.93911,67.709953
14,Afghanistan,Asia,2014,89.500000,26.10,8.95,6.940000e+06,18.93,0.16,0.0,...,868.57620,2.25,4880.000114,NaN,2.724543,614.223342,60.0,652230.0,33.93911,67.709953
15,Afghanistan,Asia,2015,71.500000,27.40,8.79,4.890000e+06,17.53,0.15,0.0,...,970.08030,2.37,5949.999809,NaN,1.451315,556.007221,60.0,652230.0,33.93911,67.709953
16,Afghanistan,Asia,2016,97.700000,28.60,9.87,8.600000e+05,19.92,0.15,0.0,...,862.79114,2.24,5300.000191,NaN,2.260314,512.012778,60.0,652230.0,33.93911,67.709953
17,Afghanistan,Asia,2017,97.700000,29.70,9.79,5.033000e+07,19.21,0.18,0.0,...,829.31195,2.30,4780.000210,NaN,2.647003,516.679862,60.0,652230.0,33.93911,67.709953
18,Afghanistan,Asia,2018,96.616135,30.90,9.55,7.010000e+07,17.96,0.20,0.0,...,924.25085,2.44,6070.000172,NaN,1.189228,485.668419,60.0,652230.0,33.93911,67.709953
19,Afghanistan,Asia,2019,97.700000,31.90,9.58,4.620000e+06,18.51,0.18,0.0,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60.0,652230.0,33.93911,67.709953
20,Afghanistan,Asia,2020,97.700000,33.20,9.35,3.296947e+07,NaN,0.12,0.0,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60.0,652230.0,33.93911,67.709953

In [11]:
df_af['financial_flows_to_developing_countries_(us_$)'].fillna(df_af["financial_flows_to_developing_countries_(us_$)"].mean(), inplace=True)
df_af.round(1)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6616\3100217697.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_af['financial_flows_to_developing_countries_(us_$)'].fillna(df_af["financial_flows_to_developing_countries_(us_$)"].mean(), inplace=True)

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.6,6.2,9.2,20000.0,45.0,0.2,0.0,...,302.6,1.6,760.0,NaN,NaN,NaN,60,652230.0,33.9,67.7
1,Afghanistan,Asia,2001,4.1,7.2,8.9,130000.0,45.6,0.1,0.0,...,236.9,1.7,730.0,NaN,NaN,NaN,60,652230.0,33.9,67.7
2,Afghanistan,Asia,2002,9.4,8.2,8.5,3950000.0,37.8,0.1,0.0,...,210.9,1.4,1030.0,NaN,NaN,179.4,60,652230.0,33.9,67.7
3,Afghanistan,Asia,2003,14.7,9.5,8.1,25970000.0,36.7,0.3,0.0,...,230.0,1.4,1220.0,NaN,8.8,190.7,60,652230.0,33.9,67.7
4,Afghanistan,Asia,2004,20.1,10.9,7.8,32969473.7,44.2,0.3,0.0,...,204.2,1.2,1030.0,NaN,1.4,211.4,60,652230.0,33.9,67.7
5,Afghanistan,Asia,2005,25.4,12.2,7.5,9830000.0,33.9,0.3,0.0,...,252.1,1.4,1550.0,NaN,11.2,242.0,60,652230.0,33.9,67.7
6,Afghanistan,Asia,2006,30.7,13.8,7.4,10620000.0,31.9,0.2,0.0,...,304.4,1.5,1760.0,NaN,5.4,263.7,60,652230.0,33.9,67.7
7,Afghanistan,Asia,2007,36.1,15.3,7.2,15750000.0,28.8,0.2,0.0,...,354.3,1.5,1770.0,NaN,13.8,359.7,60,652230.0,33.9,67.7
8,Afghanistan,Asia,2008,42.4,16.7,7.5,16170000.0,21.2,0.2,0.0,...,607.8,1.9,3560.0,NaN,3.9,364.7,60,652230.0,33.9,67.7
9,Afghanistan,Asia,2009,46.7,18.4,7.5,9960000.0,16.5,0.2,0.0,...,975.0,2.2,4880.0,NaN,21.4,437.3,60,652230.0,33.9,67.7
10,Afghanistan,Asia,2010,42.7,20.0,8.3,36500000.0,15.2,0.2,0.0,...,1182.9,2.5,7110.0,NaN,14.4,543.3,60,652230.0,33.9,67.7
11,Afghanistan,Asia,2011,43.2,21.8,8.1,28690000.0,12.6,0.2,0.0,...,1436.1,3.2,8930.0,NaN,0.4,591.2,60,652230.0,33.9,67.7
12,Afghanistan,Asia,2012,69.1,23.0,9.3,62630000.0,15.4,0.1,0.0,...,1324.1,2.6,8080.0,NaN,12.8,638.8,60,652230.0,33.9,67.7
13,Afghanistan,Asia,2013,68.3,24.8,9.1,268460000.0,16.9,0.2,0.0,...,1060.8,2.5,5990.0,NaN,5.6,624.3,60,652230.0,33.9,67.7
14,Afghanistan,Asia,2014,89.5,26.1,9.0,6940000.0,18.9,0.2,0.0,...,868.6,2.2,4880.0,NaN,2.7,614.2,60,652230.0,33.9,67.7
15,Afghanistan,Asia,2015,71.5,27.4,8.8,4890000.0,17.5,0.2,0.0,...,970.1,2.4,5950.0,NaN,1.5,556.0,60,652230.0,33.9,67.7
16,Afghanistan,Asia,2016,97.7,28.6,9.9,860000.0,19.9,0.2,0.0,...,862.8,2.2,5300.0,NaN,2.3,512.0,60,652230.0,33.9,67.7
17,Afghanistan,Asia,2017,97.7,29.7,9.8,50330000.0,19.2,0.2,0.0,...,829.3,2.3,4780.0,NaN,2.6,516.7,60,652230.0,33.9,67.7
18,Afghanistan,Asia,2018,96.6,30.9,9.6,70100000.0,18.0,0.2,0.0,...,924.3,2.4,6070.0,NaN,1.2,485.7,60,652230.0,33.9,67.7
19,Afghanistan,Asia,2019,97.7,31.9,9.6,4620000.0,18.5,0.2,0.0,...,802.6,2.4,6080.0,NaN,3.9,494.2,60,652230.0,33.9,67.7
20,Afghanistan,Asia,2020,97.7,33.2,9.4,32969473.7,NaN,0.1,0.0,...,702.9,NaN,NaN,NaN,-2.4,516.7,60,652230.0,33.9,67.7

In [130]:
df_copy = df.copy()

In [153]:
import pandas as pd

def fillna_and_round(df, entity_column, value_column):
    df_copy = df.copy()
        
    for entity in df_copy[entity_column].unique():
        df_entity = df_copy.loc[df_copy[entity_column] == entity] #para buscar el pais

        mean_value = df_entity[value_column].mean() #para aplicar la media al pais que se ha buscado

        df_entity[value_column].fillna(mean_value, inplace=True) #para reemplazar los valores nulos del pais con su propia media

        df_copy.loc[df_copy[entity_column] == entity, value_column] = df_entity[value_column]
    df_copy = df_copy.round(1)

    return df_copy

In [150]:
df_copy.head()

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(usd),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60.0,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60.0,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60.0,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60.0,652230.0,33.93911,67.709953

In [160]:
df_copy_new = fillna_and_round(df_copy, 'entity', 'financial_flows_to_developing_countries_(usd)')

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6616\3436646164.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_entity[value_column].fillna(mean_value, inplace=True) #para reemplazar los valores nulos del pais con su propia media

In [141]:

def fillna_and_round(df, entity_column, value_column):
            
    for entity in df[entity_column].unique():
        df_entity = df.loc[df[entity_column] == entity] #para buscar el pais

        mean_value = df_entity[value_column].mean() #para aplicar la media al pais que se ha buscado

        df_entity[value_column].fillna(mean_value, inplace=True) #para reemplazar los valores nulos del pais con su propia media

        df.loc[df[entity_column] == entity, value_column] = df_entity[value_column]
    df = df.round(1)

    return df

In [171]:
df1 = fillna_and_round(df, 'entity', 'financial_flows_to_developing_countries_(usd)')
df1.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_6616\3436646164.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_entity[value_column].fillna(mean_value, inplace=True) #para reemplazar los valores nulos del pais con su propia media

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(usd),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.6,6.2,9.2,20000.0,45.0,0.2,0.0,...,302.6,1.6,760.0,NaN,NaN,NaN,60.0,652230.0,33.9,67.7
1,Afghanistan,Asia,2001,4.1,7.2,8.9,130000.0,45.6,0.1,0.0,...,236.9,1.7,730.0,NaN,NaN,NaN,60.0,652230.0,33.9,67.7
2,Afghanistan,Asia,2002,9.4,8.2,8.5,3950000.0,37.8,0.1,0.0,...,210.9,1.4,1030.0,NaN,NaN,179.4,60.0,652230.0,33.9,67.7
3,Afghanistan,Asia,2003,14.7,9.5,8.1,25970000.0,36.7,0.3,0.0,...,230.0,1.4,1220.0,NaN,8.8,190.7,60.0,652230.0,33.9,67.7
4,Afghanistan,Asia,2004,20.1,10.9,7.8,32969473.7,44.2,0.3,0.0,...,204.2,1.2,1030.0,NaN,1.4,211.4,60.0,652230.0,33.9,67.7

In [172]:
df1.isnull().sum()

entity                                                                 0
continente                                                            64
year                                                                   0
access_to_electricity_(%_of_population)                               10
access_to_clean_fuels_for_cooking                                    169
renewable_electricity_generating_capacity_per_capita                 931
financial_flows_to_developing_countries_(usd)                       1184
renewable_energy_share_in_the_total_final_energy_consumption_(%)     194
electricity_from_fossil_fuels_(twh)                                   21
electricity_from_nuclear_(twh)                                       126
electricity_from_renewables_(twh)                                     21
low_carbon_electricity_(%_electricity)                                42
primary_energy_consumption_per_capita_(kwh/person)                     0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)          207
value_co2_emissions_kt_by_country                                    428
renewables_(%_equivalent_primary_energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
density_(p/km2)                                                        1
land_area(km2)                                                         1
latitude                                                               1
longitude                                                              1
dtype: int64

In [201]:
#Paises que no estan dentro del grupo continente
dl = df[df['continente'].isnull()]
dl.entity.unique()

array(['Aruba', 'Bermuda', 'Cayman Islands', 'French Guiana'],
      dtype=object)

In [ ]:
dl[dl['entity']=='United States']

In [17]:
media_pais_columna('columna')

NameError: name 'media_pais_columna' is not defined

In [ ]:
df1 = pd.read_csv("clean_regional_data.cbsv")
df1

In [ ]:
df2 = pd.read_csv("cleandata.csv")
df2

In [ ]:
df3 = pd.read_csv("cleandataTurkiye.csv")
df3

In [ ]:
df4 = pd.read_csv("new_data.csv")
df4