In [1]:
import pandas as pd

df = pd.read_csv("global-data-on-sustainable-energy.csv")
df.iloc[19:41]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
19,Afghanistan,2019,97.70,31.90,9.58,4620000.0,18.51,0.18,0.0,0.89,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.939110,67.709953
20,Afghanistan,2020,97.70,33.20,9.35,NaN,NaN,0.12,0.0,0.68,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
21,Albania,2000,100.00,38.20,NaN,NaN,NaN,0.14,0.0,4.55,...,9029.43750,4.13,3170.000000,NaN,6.946217,1126.683340,105,28748.0,41.153332,20.168331
22,Albania,2001,100.00,40.50,NaN,NaN,NaN,0.13,0.0,3.52,...,8635.53200,3.89,3230.000000,NaN,8.293313,1281.659826,105,28748.0,41.153332,20.168331
23,Albania,2002,100.00,43.20,NaN,NaN,NaN,0.16,0.0,3.48,...,9443.55500,4.10,3759.999990,NaN,4.536524,1425.124219,105,28748.0,41.153332,20.168331
24,Albania,2003,100.00,46.40,NaN,NaN,NaN,0.10,0.0,5.12,...,10756.61200,3.80,4070.000172,NaN,5.528637,1846.120121,105,28748.0,41.153332,20.168331
25,Albania,2004,100.00,49.00,NaN,NaN,NaN,0.13,0.0,5.41,...,11586.95100,3.96,4250.000000,NaN,5.514668,2373.581292,105,28748.0,41.153332,20.168331
26,Albania,2005,100.00,51.90,NaN,NaN,NaN,0.07,0.0,5.32,...,11545.61600,3.75,4030.000210,NaN,5.526424,2673.786584,105,28748.0,41.153332,20.168331
27,Albania,2006,100.00,54.80,NaN,NaN,NaN,0.09,0.0,4.95,...,10976.72800,3.46,4010.000229,NaN,5.902659,2972.742924,105,28748.0,41.153332,20.168331
28,Albania,2007,100.00,58.10,NaN,NaN,NaN,0.07,0.0,2.76,...,9534.87400,3.12,4139.999866,NaN,5.983260,3595.038057,105,28748.0,41.153332,20.168331
29,Albania,2008,100.00,60.80,NaN,NaN,NaN,0.07,0.0,3.76,...,10499.32800,3.01,4079.999924,NaN,7.500041,4370.539925,105,28748.0,41.153332,20.168331
30,Albania,2009,100.00,63.60,NaN,NaN,NaN,0.00,0.0,5.20,...,11524.42800,2.98,4219.999790,NaN,3.354289,4114.134899,105,28748.0,41.153332,20.168331
31,Albania,2010,100.00,66.50,NaN,NaN,NaN,0.00,0.0,7.49,...,12377.50400,2.85,4449.999809,NaN,3.706938,4094.348386,105,28748.0,41.153332,20.168331
32,Albania,2011,100.00,68.90,NaN,NaN,NaN,0.06,0.0,4.09,...,10854.64900,2.91,4849.999905,NaN,2.545406,4437.142612,105,28748.0,41.153332,20.168331
33,Albania,2012,99.90,71.30,NaN,NaN,NaN,0.00,0.0,4.68,...,10652.80900,2.57,4360.000134,NaN,1.417243,4247.630047,105,28748.0,41.153332,20.168331
34,Albania,2013,100.00,73.15,NaN,NaN,NaN,0.00,0.0,6.89,...,13392.77400,2.96,4440.000057,NaN,1.002018,4413.062005,105,28748.0,41.153332,20.168331
35,Albania,2014,99.95,74.60,NaN,NaN,NaN,0.00,0.0,4.68,...,11809.46100,2.93,4820.000172,NaN,1.774449,4578.633208,105,28748.0,41.153332,20.168331
36,Albania,2015,99.98,76.20,NaN,NaN,NaN,0.00,0.0,5.84,...,11824.31400,2.69,4619.999886,NaN,2.218726,3952.802538,105,28748.0,41.153332,20.168331
37,Albania,2016,99.89,77.80,NaN,NaN,NaN,0.00,0.0,7.70,...,13823.74800,2.68,4480.000019,NaN,3.314981,4124.055390,105,28748.0,41.153332,20.168331
38,Albania,2017,99.89,78.70,NaN,NaN,NaN,0.00,0.0,4.48,...,12802.36000,2.69,5139.999866,NaN,3.802227,4531.019374,105,28748.0,41.153332,20.168331
39,Albania,2018,100.00,79.80,NaN,NaN,NaN,0.00,0.0,8.47,...,14609.70100,2.57,5110.000134,NaN,4.019360,5287.663694,105,28748.0,41.153332,20.168331
40,Albania,2019,100.00,80.70,NaN,NaN,NaN,0.00,0.0,5.17,...,11585.55500,2.50,4829.999924,NaN,2.113420,5395.659532,105,28748.0,41.153332,20.168331

In [2]:
df['Entity'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'French Guiana', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Tajikistan', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [3]:
paises_continente = {
    'Afghanistan': 'Asia',
    'Albania': 'Europe',
    'Algeria': 'Africa',
    'Andorra': 'Europe',
    'Angola': 'Africa',
    'Antigua and Barbuda': 'Centro America, Caribe',
    'Argentina': 'South America',
    'Armenia': 'Asia',
    'Australia': 'Oceania',
    'Austria': 'Europe',
    'Azerbaijan': 'Asia',
    'Bahamas': 'Centro America, Caribe',
    'Bahrain': 'Asia',
    'Bangladesh': 'Asia',
    'Barbados': 'Centro America, Caribe',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Belize': 'Centro America, Caribe',
    'Benin': 'Africa',
    'Bhutan': 'Asia',
    'Bolivia': 'South America',
    'Bosnia and Herzegovina': 'Europe',
    'Botswana': 'Africa',
    'Brazil': 'South America',
    'Brunei': 'Asia',
    'Bulgaria': 'Europe',
    'Burkina Faso': 'Africa',
    'Burundi': 'Africa',
    'Cabo Verde': 'Africa',
    'Cambodia': 'Asia',
    'Cameroon': 'Africa',
    'Canada': 'North America',
    'Central African Republic': 'Africa',
    'Chad': 'Africa',
    'Chile': 'South America',
    'China': 'Asia',
    'Colombia': 'South America',
    'Comoros': 'Africa',
    'Congo': 'Africa',
    'Costa Rica': 'Centro America, Caribe',
    'Croatia': 'Europe',
    'Cuba': 'Centro America, Caribe',
    'Cyprus': 'Asia',
    'Czechia': 'Europe',
    'Denmark': 'Europe',
    'Djibouti': 'Africa',
    'Dominica': 'Centro America, Caribe',
    'Dominican Republic': 'Centro America, Caribe',
    'East Timor': 'Asia',
    'Ecuador': 'South America',
    'Egypt': 'Africa',
    'El Salvador': 'Centro America, Caribe',
    'Equatorial Guinea': 'Africa',
    'Eritrea': 'Africa',
    'Estonia': 'Europe',
    'Eswatini': 'Africa',
    'Ethiopia': 'Africa',
    'Fiji': 'Oceania',
    'Finland': 'Europe',
    'France': 'Europe',
    'Gabon': 'Africa',
    'Gambia': 'Africa',
    'Georgia': 'Asia',
    'Germany': 'Europe',
    'Ghana': 'Africa',
    'Greece': 'Europe',
    'Grenada': 'Centro America, Caribe',
    'Guatemala': 'Centro America, Caribe',
    'Guinea': 'Africa',
    'Guinea-Bissau': 'Africa',
    'Guyana': 'South America',
    'Haiti': 'Centro America, Caribe',
    'Honduras': 'Centro America, Caribe',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'India': 'Asia',
    'Indonesia': 'Asia',
    'Iran': 'Asia',
    'Iraq': 'Asia',
    'Ireland': 'Europe',
    'Israel': 'Asia',
    'Italy': 'Europe',
    'Jamaica': 'Centro America, Caribe',
    'Japan': 'Asia',
    'Jordan': 'Asia',
    'Kazakhstan': 'Asia',
    'Kenya': 'Africa',
    'Kiribati': 'Oceania',
    'Korea, North': 'Asia',
    'Korea, South': 'Asia',
    'Kosovo': 'Europe',
    'Kuwait': 'Asia',
    'Kyrgyzstan': 'Asia',
    'Laos': 'Asia',
    'Latvia': 'Europe',
    'Lebanon': 'Asia',
    'Lesotho': 'Africa',
    'Liberia': 'Africa',
    'Libya': 'Africa',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Madagascar': 'Africa',
    'Malawi': 'Africa',
    'Malaysia': 'Asia',
    'Maldives': 'Asia',
    'Mali': 'Africa',
    'Malta': 'Europe',
    'Mauritania': 'Africa',
    'Mauritius': 'Africa',
    'Mexico': 'North America',
    'Mongolia': 'Asia',
    'Montenegro': 'Europe',
    'Morocco': 'Africa',
    'Mozambique': 'Africa',
    'Myanmar': 'Asia',
    'Namibia': 'Africa',
    'Nauru': 'Oceania',
    'Nepal': 'Asia',
    'Netherlands': 'Europe',
    'New Caledonia': 'Oceania',
    'New Zealand': 'Oceania',
    'Nicaragua': 'Centro America, Caribe',
    'Niger': 'Africa',
    'Nigeria': 'Africa',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Oman': 'Asia',
    'Pakistan': 'Asia',
    'Panama': 'Centro America, Caribe',
    'Papua New Guinea': 'Oceania',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Philippines': 'Asia',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Puerto Rico': 'Centro America, Caribe',
    'Qatar': 'Asia',
    'Romania': 'Europe',
    'Rwanda': 'Africa',
    'Saint Kitts and Nevis': 'Centro America, Caribe',
    'Saint Lucia': 'Centro America, Caribe',
    'Saint Vincent and the Grenadines': 'Centro America, Caribe',
    'Samoa': 'Oceania',
    'Sao Tome and Principe': 'Africa',
    'Saudi Arabia': 'Asia',
    'Senegal': 'Africa',
    'Serbia': 'Europe',
    'Seychelles': 'Africa',
    'Sierra Leone': 'Africa',
    'Singapore': 'Asia',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Solomon Islands': 'Oceania',
    'Somalia': 'Africa',
    'South Africa': 'Africa',
    'South Sudan': 'Africa',
    'Spain': 'Europe',
    'Sri Lanka': 'Asia',
    'Sudan': 'Africa',
    'Suriname': 'South America',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Tajikistan': 'Asia',
    'Thailand': 'Asia',
    'Togo': 'Africa',
    'Tonga': 'Oceania',
    'Trinidad and Tobago': 'Centro America, Caribe',
    'Tunisia': 'Africa',
    'Turkey': 'Asia',
    'Turkmenistan': 'Asia',
    'Tuvalu': 'Oceania',
    'Uganda': 'Africa',
    'Ukraine': 'Europe',
    'United Arab Emirates': 'Asia',
    'United Kingdom': 'Europe',
    'United States': 'North America',
    'Uruguay': 'South America',
    'Uzbekistan': 'Asia',
    'Vanuatu': 'Oceania',
    'Yemen': 'Asia',
    'Zambia': 'Africa',
    'Zimbabwe': 'Africa'
}

In [4]:
df['Continente'] = df['Entity'].map(paises_continente)
df.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude,Continente
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,Asia
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953,Asia
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953,Asia
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953,Asia
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953,Asia

In [5]:
df['Continente'] = df['Entity'].map(paises_continente)
columna_continente = df.pop('Continente')
df.insert(1, 'Continente', columna_continente)
df.head()

,Entity,Continente,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,Asia,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [6]:
df.columns = [e.lower().replace(" ", "_").replace("\n","_").replace("-","_").replace("\\n","_") for e in df.columns]
df.head()

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [15]:
df.loc[df['entity']=='Afghanistan']

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,Asia,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,Asia,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,Asia,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,Asia,2004,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953
5,Afghanistan,Asia,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,...,252.06912,1.41,1549.999952,NaN,11.229715,242.031313,60,652230.0,33.93911,67.709953
6,Afghanistan,Asia,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,...,304.42090,1.50,1759.999990,NaN,5.357403,263.733602,60,652230.0,33.93911,67.709953
7,Afghanistan,Asia,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60,652230.0,33.93911,67.709953
8,Afghanistan,Asia,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60,652230.0,33.93911,67.709953
9,Afghanistan,Asia,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,...,975.04816,2.25,4880.000114,NaN,21.390528,437.268740,60,652230.0,33.93911,67.709953
10,Afghanistan,Asia,2010,42.700000,20.00,8.27,36500000.0,15.15,0.19,0.0,...,1182.89200,2.46,7110.000134,NaN,14.362441,543.306526,60,652230.0,33.93911,67.709953
11,Afghanistan,Asia,2011,43.222020,21.80,8.13,28690000.0,12.61,0.18,0.0,...,1436.11430,3.23,8930.000305,NaN,0.426355,591.190030,60,652230.0,33.93911,67.709953
12,Afghanistan,Asia,2012,69.100000,23.00,9.29,62630000.0,15.36,0.14,0.0,...,1324.12110,2.61,8079.999924,NaN,12.752287,638.845852,60,652230.0,33.93911,67.709953
13,Afghanistan,Asia,2013,68.290650,24.80,9.10,268460000.0,16.86,0.22,0.0,...,1060.79260,2.46,5989.999771,NaN,5.600745,624.315454,60,652230.0,33.93911,67.709953
14,Afghanistan,Asia,2014,89.500000,26.10,8.95,6940000.0,18.93,0.16,0.0,...,868.57620,2.25,4880.000114,NaN,2.724543,614.223342,60,652230.0,33.93911,67.709953
15,Afghanistan,Asia,2015,71.500000,27.40,8.79,4890000.0,17.53,0.15,0.0,...,970.08030,2.37,5949.999809,NaN,1.451315,556.007221,60,652230.0,33.93911,67.709953
16,Afghanistan,Asia,2016,97.700000,28.60,9.87,860000.0,19.92,0.15,0.0,...,862.79114,2.24,5300.000191,NaN,2.260314,512.012778,60,652230.0,33.93911,67.709953
17,Afghanistan,Asia,2017,97.700000,29.70,9.79,50330000.0,19.21,0.18,0.0,...,829.31195,2.30,4780.000210,NaN,2.647003,516.679862,60,652230.0,33.93911,67.709953
18,Afghanistan,Asia,2018,96.616135,30.90,9.55,70100000.0,17.96,0.20,0.0,...,924.25085,2.44,6070.000172,NaN,1.189228,485.668419,60,652230.0,33.93911,67.709953
19,Afghanistan,Asia,2019,97.700000,31.90,9.58,4620000.0,18.51,0.18,0.0,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.93911,67.709953
20,Afghanistan,Asia,2020,97.700000,33.20,9.35,NaN,NaN,0.12,0.0,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.93911,67.709953

In [38]:
xxx = df['financial_flows_to_developing_countries_(us_$)'][0:21].mean()

In [31]:
df_af = df.loc[df['entity']=='Afghanistan']
df_af_mean = df_af.fillna(df_af["financial_flows_to_developing_countries_(us_$)"].mean()).round(1)
df_af_mean

,entity,continente,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable_electricity_generating_capacity_per_capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density_(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,Asia,2000,1.6,6.2,9.2,20000.0,45.0,0.2,0.0,...,302.6,1.6,760.0,32969473.7,32969473.7,32969473.7,60,652230.0,33.9,67.7
1,Afghanistan,Asia,2001,4.1,7.2,8.9,130000.0,45.6,0.1,0.0,...,236.9,1.7,730.0,32969473.7,32969473.7,32969473.7,60,652230.0,33.9,67.7
2,Afghanistan,Asia,2002,9.4,8.2,8.5,3950000.0,37.8,0.1,0.0,...,210.9,1.4,1030.0,32969473.7,32969473.7,179.4,60,652230.0,33.9,67.7
3,Afghanistan,Asia,2003,14.7,9.5,8.1,25970000.0,36.7,0.3,0.0,...,230.0,1.4,1220.0,32969473.7,8.8,190.7,60,652230.0,33.9,67.7
4,Afghanistan,Asia,2004,20.1,10.9,7.8,32969473.7,44.2,0.3,0.0,...,204.2,1.2,1030.0,32969473.7,1.4,211.4,60,652230.0,33.9,67.7
5,Afghanistan,Asia,2005,25.4,12.2,7.5,9830000.0,33.9,0.3,0.0,...,252.1,1.4,1550.0,32969473.7,11.2,242.0,60,652230.0,33.9,67.7
6,Afghanistan,Asia,2006,30.7,13.8,7.4,10620000.0,31.9,0.2,0.0,...,304.4,1.5,1760.0,32969473.7,5.4,263.7,60,652230.0,33.9,67.7
7,Afghanistan,Asia,2007,36.1,15.3,7.2,15750000.0,28.8,0.2,0.0,...,354.3,1.5,1770.0,32969473.7,13.8,359.7,60,652230.0,33.9,67.7
8,Afghanistan,Asia,2008,42.4,16.7,7.5,16170000.0,21.2,0.2,0.0,...,607.8,1.9,3560.0,32969473.7,3.9,364.7,60,652230.0,33.9,67.7
9,Afghanistan,Asia,2009,46.7,18.4,7.5,9960000.0,16.5,0.2,0.0,...,975.0,2.2,4880.0,32969473.7,21.4,437.3,60,652230.0,33.9,67.7
10,Afghanistan,Asia,2010,42.7,20.0,8.3,36500000.0,15.2,0.2,0.0,...,1182.9,2.5,7110.0,32969473.7,14.4,543.3,60,652230.0,33.9,67.7
11,Afghanistan,Asia,2011,43.2,21.8,8.1,28690000.0,12.6,0.2,0.0,...,1436.1,3.2,8930.0,32969473.7,0.4,591.2,60,652230.0,33.9,67.7
12,Afghanistan,Asia,2012,69.1,23.0,9.3,62630000.0,15.4,0.1,0.0,...,1324.1,2.6,8080.0,32969473.7,12.8,638.8,60,652230.0,33.9,67.7
13,Afghanistan,Asia,2013,68.3,24.8,9.1,268460000.0,16.9,0.2,0.0,...,1060.8,2.5,5990.0,32969473.7,5.6,624.3,60,652230.0,33.9,67.7
14,Afghanistan,Asia,2014,89.5,26.1,9.0,6940000.0,18.9,0.2,0.0,...,868.6,2.2,4880.0,32969473.7,2.7,614.2,60,652230.0,33.9,67.7
15,Afghanistan,Asia,2015,71.5,27.4,8.8,4890000.0,17.5,0.2,0.0,...,970.1,2.4,5950.0,32969473.7,1.5,556.0,60,652230.0,33.9,67.7
16,Afghanistan,Asia,2016,97.7,28.6,9.9,860000.0,19.9,0.2,0.0,...,862.8,2.2,5300.0,32969473.7,2.3,512.0,60,652230.0,33.9,67.7
17,Afghanistan,Asia,2017,97.7,29.7,9.8,50330000.0,19.2,0.2,0.0,...,829.3,2.3,4780.0,32969473.7,2.6,516.7,60,652230.0,33.9,67.7
18,Afghanistan,Asia,2018,96.6,30.9,9.6,70100000.0,18.0,0.2,0.0,...,924.3,2.4,6070.0,32969473.7,1.2,485.7,60,652230.0,33.9,67.7
19,Afghanistan,Asia,2019,97.7,31.9,9.6,4620000.0,18.5,0.2,0.0,...,802.6,2.4,6080.0,32969473.7,3.9,494.2,60,652230.0,33.9,67.7
20,Afghanistan,Asia,2020,97.7,33.2,9.4,32969473.7,32969473.7,0.1,0.0,...,702.9,32969473.7,32969473.7,32969473.7,-2.4,516.7,60,652230.0,33.9,67.7

In [8]:
df1 = pd.read_csv("clean_regional_data.cbsv")
df1

,Country,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),...,"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)","Electricity production from oil, gas and coal sources (% of total)","Industry (including construction), value added (annual % growth)","Industry (including construction), value added (current US$)",Employment in industry (% of total employment) (modeled ILO estimate),Urban population growth (annual %),Urban population,Research and development expenditure (% of GDP),"Foreign direct investment, net inflows (% of GDP)","Foreign direct investment, net outflows (% of GDP)"
0,Africa Eastern and Southern,2000,11.580366,19.957302,773.979507,71.504193,13.086301,0.000720,4.681261,2.016792,...,219.527730,73.521705,6.121018,7.665491e+10,9.763503,3.602262,115551653,0.458402,1.553444,0.118004
1,Africa Eastern and Southern,2001,11.907943,19.975365,737.413463,71.157463,14.547248,0.000705,3.780810,1.780885,...,218.590249,72.939054,1.976993,6.975842e+10,9.818520,3.655377,119775502,0.458402,4.822047,-1.488837
2,Africa Eastern and Southern,2002,12.285175,21.576500,762.543066,70.657125,15.062843,0.001343,4.026182,1.600265,...,211.482793,72.258733,4.271120,7.326761e+10,9.908931,3.716958,124227507,0.528556,2.487862,-0.104442
3,Africa Eastern and Southern,2003,12.607641,22.529265,768.235039,71.554647,13.928695,0.000964,4.069472,1.681714,...,214.297045,73.237325,1.848180,9.469750e+10,9.890159,3.708082,128833965,0.594807,2.478118,0.249632
4,Africa Eastern and Southern,2004,12.990589,23.749531,771.962501,71.046595,13.895482,0.112369,4.092130,2.028459,...,212.854659,73.187423,6.690178,1.191500e+11,9.939811,3.736205,133647466,0.626331,1.859474,0.497309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,World,2016,65.005668,88.192385,647.639462,2.441195,35.919408,28.765752,0.565417,20.685859,...,166.498142,51.892806,2.851126,2.010580e+13,23.059705,2.036862,4066425788,2.137829,3.522494,2.753159
1004,World,2017,66.321819,89.019548,647.639462,2.441195,35.919408,28.765752,0.565417,20.685859,...,166.498142,51.892806,3.686472,2.179630e+13,22.913670,1.992037,4147430481,2.133375,2.664819,2.536390
1005,World,2018,67.696517,89.893733,647.639462,2.441195,35.919408,28.765752,0.565417,20.685859,...,166.498142,51.892806,3.373584,2.355380e+13,22.825949,1.929135,4227440026,2.196050,0.989692,0.765036
1006,World,2019,68.921601,90.194716,647.639462,2.441195,35.919408,28.765752,0.565417,20.685859,...,166.498142,51.892806,1.837852,2.343220e+13,22.795863,1.864506,4306260905,2.331934,2.081529,1.689919
1007,World,2020,70.184805,90.483629,647.639462,2.441195,35.919408,28.765752,0.565417,20.685859,...,166.498142,51.892806,-2.352103,2.230290e+13,22.625118,1.798295,4383700170,2.627081,1.366807,1.132252

In [9]:
df2 = pd.read_csv("cleandata.csv")
df2

,Country,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),...,"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)","Electricity production from oil, gas and coal sources (% of total)","Industry (including construction), value added (annual % growth)","Industry (including construction), value added (current US$)",Employment in industry (% of total employment) (modeled ILO estimate),Urban population growth (annual %),Urban population,Research and development expenditure (% of GDP),"Foreign direct investment, net inflows (% of GDP)","Foreign direct investment, net outflows (% of GDP)"
0,Afghanistan,2000,6.7,4.446891,322.474811,0.000000,32.892735,0.000000,0.0,66.947436,...,63.484046,66.947436,5.655930,6.298994e+09,8.636017,1.861377,4314700,0.153124,1.344717,0.116357
1,Afghanistan,2001,7.7,9.294527,340.563993,0.000000,32.322381,0.000000,0.0,67.513679,...,60.286446,67.513679,6.244025,7.161409e+09,8.361796,1.153839,4364773,0.149760,1.475247,0.121433
2,Afghanistan,2002,8.8,14.133616,844.470476,2.605560,13.753974,44.591457,0.0,10.746954,...,223.763298,57.943971,-0.311996,9.176983e+08,9.271434,6.863453,4674867,0.195436,1.297274,0.154313
3,Afghanistan,2003,10.0,18.971165,717.851644,2.170395,31.123784,35.506266,0.0,8.619140,...,144.010334,46.295801,10.269693,1.030959e+09,9.739044,7.953448,5061866,0.195436,1.273269,0.022029
4,Afghanistan,2004,11.1,23.814182,585.202613,2.605560,13.753974,44.591457,0.0,10.746954,...,138.764435,57.943971,17.476076,1.369255e+09,10.109770,4.588653,5299549,0.195436,3.579894,-0.013408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,Zimbabwe,2016,30.0,42.465588,828.513954,51.100526,48.092216,0.000000,0.0,0.460341,...,333.606836,51.560867,1.486909,4.544352e+09,8.565043,1.806610,4667645,0.193420,1.669274,0.155728
4007,Zimbabwe,2017,29.8,43.979065,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,285.992232,53.933498,2.591915,3.764046e+09,9.348268,1.860765,4755312,0.193420,1.746885,0.005315
4008,Zimbabwe,2018,30.0,45.400288,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,285.992232,53.933498,3.654325,1.060133e+10,10.226750,1.933653,4848158,0.193420,2.101721,0.002303
4009,Zimbabwe,2019,30.2,46.682095,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,290.096823,53.933498,-8.587173,6.991980e+09,11.195960,1.992351,4945719,0.193420,1.142806,0.011010
4010,Zimbabwe,2020,30.3,52.747667,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,290.096823,53.933498,-8.244479,7.048194e+09,11.254040,2.130421,5052214,0.193420,0.699034,-0.016272

In [10]:
df3 = pd.read_csv("cleandataTurkiye.csv")
df3

,Country,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),...,"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)","Electricity production from oil, gas and coal sources (% of total)","Industry (including construction), value added (annual % growth)","Industry (including construction), value added (current US$)",Employment in industry (% of total employment) (modeled ILO estimate),Urban population growth (annual %),Urban population,Research and development expenditure (% of GDP),"Foreign direct investment, net inflows (% of GDP)","Foreign direct investment, net outflows (% of GDP)"
0,Afghanistan,2000,6.7,4.446891,322.474811,0.000000,32.892735,0.000000,0.0,66.947436,...,63.484046,66.947436,5.655930,6.298994e+09,8.636017,1.861377,4314700,0.153124,1.344717,0.116357
1,Afghanistan,2001,7.7,9.294527,340.563993,0.000000,32.322381,0.000000,0.0,67.513679,...,60.286446,67.513679,6.244025,7.161409e+09,8.361796,1.153839,4364773,0.149760,1.475247,0.121433
2,Afghanistan,2002,8.8,14.133616,844.470476,2.605560,13.753974,44.591457,0.0,10.746954,...,223.763298,57.943971,-0.311996,9.176983e+08,9.271434,6.863453,4674867,0.195436,1.297274,0.154313
3,Afghanistan,2003,10.0,18.971165,717.851644,2.170395,31.123784,35.506266,0.0,8.619140,...,144.010334,46.295801,10.269693,1.030959e+09,9.739044,7.953448,5061866,0.195436,1.273269,0.022029
4,Afghanistan,2004,11.1,23.814182,585.202613,2.605560,13.753974,44.591457,0.0,10.746954,...,138.764435,57.943971,17.476076,1.369255e+09,10.109770,4.588653,5299549,0.195436,3.579894,-0.013408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,Zimbabwe,2016,30.0,42.465588,828.513954,51.100526,48.092216,0.000000,0.0,0.460341,...,333.606836,51.560867,1.486909,4.544352e+09,8.565043,1.806610,4667645,0.193420,1.669274,0.155728
4007,Zimbabwe,2017,29.8,43.979065,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,285.992232,53.933498,2.591915,3.764046e+09,9.348268,1.860765,4755312,0.193420,1.746885,0.005315
4008,Zimbabwe,2018,30.0,45.400288,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,285.992232,53.933498,3.654325,1.060133e+10,10.226750,1.933653,4848158,0.193420,2.101721,0.002303
4009,Zimbabwe,2019,30.2,46.682095,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,290.096823,53.933498,-8.587173,6.991980e+09,11.195960,1.992351,4945719,0.193420,1.142806,0.011010
4010,Zimbabwe,2020,30.3,52.747667,1170.102597,42.562993,40.428585,8.904288,0.0,2.466217,...,290.096823,53.933498,-8.244479,7.048194e+09,11.254040,2.130421,5052214,0.193420,0.699034,-0.016272

In [11]:
df4 = pd.read_csv("new_data.csv")
df4

,Country,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Electric power consumption (kWh per capita),Electricity production from coal sources (% of total),Electricity production from hydroelectric sources (% of total),Electricity production from natural gas sources (% of total),Electricity production from nuclear sources (% of total),Electricity production from oil sources (% of total),...,"Energy use (kg of oil equivalent) per $1,000 GDP (constant 2017 PPP)","Electricity production from oil, gas and coal sources (% of total)","Industry (including construction), value added (annual % growth)","Industry (including construction), value added (current US$)",Employment in industry (% of total employment) (modeled ILO estimate),Urban population growth (annual %),Urban population,Research and development expenditure (% of GDP),"Foreign direct investment, net inflows (% of GDP)","Foreign direct investment, net outflows (% of GDP)"
0,Afghanistan,2000,6.700000,4.446891,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.636017,1.861377,4314700,NaN,NaN,NaN
1,Afghanistan,2001,7.700000,9.294527,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.361796,1.153839,4364773,NaN,NaN,NaN
2,Afghanistan,2002,8.800000,14.133616,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.176983e+08,9.271434,6.863453,4674867,NaN,1.297274,NaN
3,Afghanistan,2003,10.000000,18.971165,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,10.269693,1.030959e+09,9.739044,7.953448,5061866,NaN,1.273269,0.022029
4,Afghanistan,2004,11.100000,23.814182,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,17.476076,1.369255e+09,10.109770,4.588653,5299549,NaN,3.579894,-0.013408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5014,World,2016,65.005668,88.192385,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.851126,2.010580e+13,23.059705,2.036862,4066425788,2.137829,3.522494,2.753159
5015,World,2017,66.321819,89.019548,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.686472,2.179630e+13,22.913670,1.992037,4147430481,2.133375,2.664819,2.536390
5016,World,2018,67.696517,89.893733,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.373584,2.355380e+13,22.825949,1.929135,4227440026,2.196050,0.989692,0.765036
5017,World,2019,68.921601,90.194716,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.837852,2.343220e+13,22.795863,1.864506,4306260905,2.331934,2.081529,1.689919
5018,World,2020,70.184805,90.483629,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-2.352103,2.230290e+13,22.625118,1.798295,4383700170,2.627081,1.366807,1.132252